# Build the app image
FROM python:3.11

ENV APP_HOME=/home/app

COPY . $APP_HOME/api

RUN groupadd app \
    && useradd -g app app \
    && chown -R app:app ${APP_HOME} \
    && cd ${APP_HOME}/api \
    && pip install -r requirements-dev.txt \
    && pip install -e .

WORKDIR $APP_HOME/api

USER app

EXPOSE 8000

CMD ["uvicorn","pamps.app:app","--host=0.0.0.0","--port=8000","--reload"]