"""like

Revision ID: 6cbfd5f195bd
Revises: eac69283f7cd
Create Date: 2024-07-08 19:20:10.856199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cbfd5f195bd'
down_revision: Union[str, None] = 'eac69283f7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_like_constraint', 'like', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_like_constraint', 'like', type_='unique')
    # ### end Alembic commands ###
