"""social

Revision ID: aac65c34bb9e
Revises: 95f8725863a4
Create Date: 2024-05-27 06:11:51.815448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aac65c34bb9e'
down_revision: Union[str, None] = '95f8725863a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_follow_constraint', 'social', ['from_id', 'to_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_follow_constraint', 'social', type_='unique')
    # ### end Alembic commands ###
